/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 8.1 and the Signal Processing Toolbox 6.19.
 * Generated on: 18-Jan-2020 01:16:14
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 1
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
//#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * E:\Soft_Installation\MATLAB\extern\include\tmwtypes.h 
 */
#define NUM_SECTIONS 3

int a[NUM_SECTIONS ][3] = {
  {
    0.03456650632617,                 0,                 0 
  },
  {
                   1,                 2,                 1 
  },
  {
     0.8912509381337,                 0,                 0 
  }
};

int b[NUM_SECTIONS ][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.515684435057,   0.6539504603614 
  },
  {
                   1,                 0,                 0 
  }
};
